// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Suendenbock_App.Data;

#nullable disable

namespace Suendenbock_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Abenteuerrang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abenteuerraenge");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Anmeldungsstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anmeldungsstati");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Beruf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Berufe");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Blutgruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Besonderheiten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blutgruppen");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BerufId")
                        .HasColumnType("int");

                    b.Property<int?>("BlutgruppeId")
                        .HasColumnType("int");

                    b.Property<int>("CompletionLevel")
                        .HasColumnType("int");

                    b.Property<int>("EindruckId")
                        .HasColumnType("int");

                    b.Property<string>("Geburtsdatum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<int?>("HausId")
                        .HasColumnType("int");

                    b.Property<int?>("HerkunftslandId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InfanterieId")
                        .HasColumnType("int");

                    b.Property<int?>("InfanterierangId")
                        .HasColumnType("int");

                    b.Property<int>("LebensstatusId")
                        .HasColumnType("int");

                    b.Property<int?>("MutterId")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RasseId")
                        .HasColumnType("int");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int");

                    b.Property<int?>("StandId")
                        .HasColumnType("int");

                    b.Property<int?>("VaterId")
                        .HasColumnType("int");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BerufId");

                    b.HasIndex("BlutgruppeId");

                    b.HasIndex("EindruckId");

                    b.HasIndex("GuildId");

                    b.HasIndex("HausId");

                    b.HasIndex("HerkunftslandId");

                    b.HasIndex("InfanterieId");

                    b.HasIndex("InfanterierangId");

                    b.HasIndex("LebensstatusId");

                    b.HasIndex("MutterId");

                    b.HasIndex("RasseId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("StandId");

                    b.HasIndex("VaterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.CharacterAffiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<int?>("InfanterieId")
                        .HasColumnType("int");

                    b.Property<int?>("InfanterierangId")
                        .HasColumnType("int");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("InfanterieId");

                    b.HasIndex("InfanterierangId");

                    b.HasIndex("ReligionId");

                    b.ToTable("CharacterAffiliations");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.CharacterDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BerufId")
                        .HasColumnType("int");

                    b.Property<int?>("BlutgruppeId")
                        .HasColumnType("int");

                    b.Property<int?>("BodyHeight")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("HausId")
                        .HasColumnType("int");

                    b.Property<int?>("HerkunftslandId")
                        .HasColumnType("int");

                    b.Property<int?>("StandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BerufId");

                    b.HasIndex("BlutgruppeId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("HausId");

                    b.HasIndex("HerkunftslandId");

                    b.HasIndex("StandId");

                    b.ToTable("CharacterDetails");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.CharacterMagicClass", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("MagicClassId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("MagicClassSpecializationId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "MagicClassId");

                    b.HasIndex("MagicClassId");

                    b.HasIndex("MagicClassSpecializationId");

                    b.ToTable("CharacterMagicClasses");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Eindruck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eindruecke");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Grundzauber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Effekt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MagicClassId")
                        .HasColumnType("int");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<string>("Spruch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stufe")
                        .HasColumnType("int");

                    b.Property<string>("Wirkung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZaubertypID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MagicClassId");

                    b.HasIndex("ZaubertypID");

                    b.ToTable("Grundzauber");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbenteuerrangId")
                        .HasColumnType("int");

                    b.Property<int>("AnmeldungsstatusId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LightCardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("leader")
                        .HasColumnType("int");

                    b.Property<int?>("vertreter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbenteuerrangId");

                    b.HasIndex("AnmeldungsstatusId");

                    b.HasIndex("LightCardId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Haus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Haeuser");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Herkunftsland", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Herkunftslaender");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Infanterie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LightCardId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("leader")
                        .HasColumnType("int");

                    b.Property<int?>("vertreter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Infanterien");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Infanterierang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Infanterieraenge");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Lebensstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lebensstati");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.LightCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CssClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farbcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LightCards");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.MagicClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObermagieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObermagieId");

                    b.ToTable("MagicClasses");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.MagicClassSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MagicClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MagicClassId");

                    b.ToTable("MagicClassSpecializations");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Obermagie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LightCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LightCardId");

                    b.ToTable("Obermagien");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Rasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rassen");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.SpecialZauber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Effekt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MagicClassSpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<string>("Spruch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stufe")
                        .HasColumnType("int");

                    b.Property<string>("Wirkung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZaubertypID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MagicClassSpecializationId");

                    b.HasIndex("ZaubertypID");

                    b.ToTable("SpecialZauber");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Stand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staende");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Zaubertyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zaubertypen");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Character", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.Beruf", null)
                        .WithMany("Characters")
                        .HasForeignKey("BerufId");

                    b.HasOne("Suendenbock_App.Models.Domain.Blutgruppe", null)
                        .WithMany("Charaktere")
                        .HasForeignKey("BlutgruppeId");

                    b.HasOne("Suendenbock_App.Models.Domain.Eindruck", "Eindruck")
                        .WithMany("Charaktere")
                        .HasForeignKey("EindruckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Guild", null)
                        .WithMany("Characters")
                        .HasForeignKey("GuildId");

                    b.HasOne("Suendenbock_App.Models.Domain.Haus", null)
                        .WithMany("Characters")
                        .HasForeignKey("HausId");

                    b.HasOne("Suendenbock_App.Models.Domain.Herkunftsland", null)
                        .WithMany("Characters")
                        .HasForeignKey("HerkunftslandId");

                    b.HasOne("Suendenbock_App.Models.Domain.Infanterie", null)
                        .WithMany("Characters")
                        .HasForeignKey("InfanterieId");

                    b.HasOne("Suendenbock_App.Models.Domain.Infanterierang", null)
                        .WithMany("Characters")
                        .HasForeignKey("InfanterierangId");

                    b.HasOne("Suendenbock_App.Models.Domain.Lebensstatus", "Lebensstatus")
                        .WithMany("Characters")
                        .HasForeignKey("LebensstatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Character", "Mutter")
                        .WithMany()
                        .HasForeignKey("MutterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Suendenbock_App.Models.Domain.Rasse", "Rasse")
                        .WithMany("Characters")
                        .HasForeignKey("RasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Religion", null)
                        .WithMany("Characters")
                        .HasForeignKey("ReligionId");

                    b.HasOne("Suendenbock_App.Models.Domain.Stand", null)
                        .WithMany("Characters")
                        .HasForeignKey("StandId");

                    b.HasOne("Suendenbock_App.Models.Domain.Character", "Vater")
                        .WithMany()
                        .HasForeignKey("VaterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Eindruck");

                    b.Navigation("Lebensstatus");

                    b.Navigation("Mutter");

                    b.Navigation("Rasse");

                    b.Navigation("Vater");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.CharacterAffiliation", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.Character", "Character")
                        .WithOne("Affiliation")
                        .HasForeignKey("Suendenbock_App.Models.Domain.CharacterAffiliation", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.HasOne("Suendenbock_App.Models.Domain.Infanterie", "Infanterie")
                        .WithMany()
                        .HasForeignKey("InfanterieId");

                    b.HasOne("Suendenbock_App.Models.Domain.Infanterierang", "Infanterierang")
                        .WithMany()
                        .HasForeignKey("InfanterierangId");

                    b.HasOne("Suendenbock_App.Models.Domain.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.Navigation("Character");

                    b.Navigation("Guild");

                    b.Navigation("Infanterie");

                    b.Navigation("Infanterierang");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.CharacterDetails", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.Beruf", "Beruf")
                        .WithMany()
                        .HasForeignKey("BerufId");

                    b.HasOne("Suendenbock_App.Models.Domain.Blutgruppe", "Blutgruppe")
                        .WithMany()
                        .HasForeignKey("BlutgruppeId");

                    b.HasOne("Suendenbock_App.Models.Domain.Character", "Character")
                        .WithOne("Details")
                        .HasForeignKey("Suendenbock_App.Models.Domain.CharacterDetails", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Haus", "Haus")
                        .WithMany()
                        .HasForeignKey("HausId");

                    b.HasOne("Suendenbock_App.Models.Domain.Herkunftsland", "Herkunftsland")
                        .WithMany()
                        .HasForeignKey("HerkunftslandId");

                    b.HasOne("Suendenbock_App.Models.Domain.Stand", "Stand")
                        .WithMany()
                        .HasForeignKey("StandId");

                    b.Navigation("Beruf");

                    b.Navigation("Blutgruppe");

                    b.Navigation("Character");

                    b.Navigation("Haus");

                    b.Navigation("Herkunftsland");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.CharacterMagicClass", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.Character", "Character")
                        .WithMany("CharacterMagicClasses")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.MagicClass", "MagicClass")
                        .WithMany("CharacterMagicClasses")
                        .HasForeignKey("MagicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.MagicClassSpecialization", "MagicClassSpecialization")
                        .WithMany()
                        .HasForeignKey("MagicClassSpecializationId");

                    b.Navigation("Character");

                    b.Navigation("MagicClass");

                    b.Navigation("MagicClassSpecialization");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Grundzauber", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.MagicClass", "MagicClass")
                        .WithMany()
                        .HasForeignKey("MagicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Zaubertyp", null)
                        .WithMany("Grundzaubers")
                        .HasForeignKey("ZaubertypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MagicClass");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Guild", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.Abenteuerrang", "AbenteuerrangNavigation")
                        .WithMany("Guilds")
                        .HasForeignKey("AbenteuerrangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Anmeldungsstatus", "AnmeldungsstatusNavigation")
                        .WithMany("Guilds")
                        .HasForeignKey("AnmeldungsstatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.LightCard", "LightCard")
                        .WithMany()
                        .HasForeignKey("LightCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbenteuerrangNavigation");

                    b.Navigation("AnmeldungsstatusNavigation");

                    b.Navigation("LightCard");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.MagicClass", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.Obermagie", "Obermagie")
                        .WithMany()
                        .HasForeignKey("ObermagieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obermagie");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.MagicClassSpecialization", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.MagicClass", "MagicClass")
                        .WithMany("MagicClassSpecializations")
                        .HasForeignKey("MagicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MagicClass");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Obermagie", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.LightCard", "LightCard")
                        .WithMany("Obermagie")
                        .HasForeignKey("LightCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LightCard");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.SpecialZauber", b =>
                {
                    b.HasOne("Suendenbock_App.Models.Domain.MagicClassSpecialization", "MagicClassSpecialization")
                        .WithMany()
                        .HasForeignKey("MagicClassSpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suendenbock_App.Models.Domain.Zaubertyp", null)
                        .WithMany("SpecialZaubers")
                        .HasForeignKey("ZaubertypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MagicClassSpecialization");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Abenteuerrang", b =>
                {
                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Anmeldungsstatus", b =>
                {
                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Beruf", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Blutgruppe", b =>
                {
                    b.Navigation("Charaktere");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Character", b =>
                {
                    b.Navigation("Affiliation");

                    b.Navigation("CharacterMagicClasses");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Eindruck", b =>
                {
                    b.Navigation("Charaktere");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Guild", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Haus", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Herkunftsland", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Infanterie", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Infanterierang", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Lebensstatus", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.LightCard", b =>
                {
                    b.Navigation("Obermagie");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.MagicClass", b =>
                {
                    b.Navigation("CharacterMagicClasses");

                    b.Navigation("MagicClassSpecializations");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Rasse", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Religion", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Stand", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Suendenbock_App.Models.Domain.Zaubertyp", b =>
                {
                    b.Navigation("Grundzaubers");

                    b.Navigation("SpecialZaubers");
                });
#pragma warning restore 612, 618
        }
    }
}
